//
//  CameraV1.swift
//  Bme
//
//  Created by parry on 2/9/17.
//  Copyright (c) 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Camera : NSObject {

    //// Cache

    private struct Cache {
        static let baseColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
    }

    //// Colors

    public class var baseColor: UIColor { return Cache.baseColor }

    //// Drawing Methods

    public class func drawCameraLogo(radius radius: CGFloat = 4) {
        //// Color Declarations
        let color2 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 46, y: 24, width: 133, height: 64), cornerRadius: radius)
        UIColor.black.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(roundedRect: CGRect(x: 52, y: 13, width: 14, height: 27), cornerRadius: radius)
        UIColor.black.setFill()
        rectangle2Path.fill()


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalIn: CGRect(x: 75, y: 15, width: 81, height: 81))
        color2.setFill()
        ovalPath.fill()


        //// Oval 3 Drawing
        let oval3Path = UIBezierPath(ovalIn: CGRect(x: 92, y: 32, width: 47, height: 47))
        CameraV1.baseColor.setFill()
        oval3Path.fill()
    }

    public class func drawCameraLens() {

        //// Oval 2 Drawing
        let oval2Path = UIBezierPath(ovalIn: CGRect(x: 81, y: 21, width: 69, height: 69))
        UIColor.green.setFill()
        oval2Path.fill()
    }

}
